### ISSUE TITLE
Bug on complex-numbers test

### ISSUE THREAD

**Issue by AfterRace** [exercism/c#1013]
All tests for the function `c_abs()` are against the same result 5.0.
So the following code pass all the tests.

```
double c_abs(complex_t x)
{
  (void)x;
  return 5.0;
}
```

I'd like to fix this bug, in order to send my first pull-request if someone explain me the process to do.

**Comment by AfterRace** [comment]
Furthermore the fact that all the functions are badly defined in `complex_number.c` files, this is not the right way to implement TDD. 
If it possible I would remove them.

**Comment by siebenschlaefer** [comment]
You're right, the [five tests](https://github.com/exercism/c/blob/main/exercises/practice/complex-numbers/test_complex_numbers.c#L243-L300) for the function `c_abs()` all expect the result `5.0`. To me it looks like the authors did that on purpose to demonstrate how different `real` and `imaginary` parts can result in the same absolute value. But I understand why that might not be ideal.

Also, the tests here at Exercism are not meant to be exhaustive. They should guide the student and catch some common bugs. They are not intended to catch each and every possible bug. IMHO a solution where `c_abs()` returns the fixed value `5.0` is not trying to solve the exercise, it tries to exploit the tests.

The description and the tests come from the language-agnostic [problem-specification](https://github.com/exercism/problem-specifications/blob/main/exercises/complex-numbers/canonical-data.json#L233-L282) repository. If you want to propose additional tests, please do that in the [forum](https://forum.exercism.org/c/exercism/bugs-and-features/126) so that everybody can participate in the discussion.

---

> Furthermore the fact that all the functions are badly defined in complex_number.c files, this is not the right way to implement TDD.

I'm sorry I do not understand. Real TDD would be hard to do because the students would have to write their own tests (in advance). Exercism's approach is rather "TDD-adjacent": If you want you can enable each tests separately, so that you can focus on one test at a time.

There have been discussions in the past whether we should define some stubs in the `.c` file or declare functions in the `.h` file. Some argued that the students will have to read and understand the tests, so they can be expected to be able to extract the names and signatures of the functions from the tests. Others argued that this does not provide any additional value for the students and that most tracks here at Exercism have those stubs.

**Comment by wolf99** [comment]
Hey, thanks for identifying  this problem and raising this issue!

The tests follow the specification in the problem-specifications repo here: https://github.com/exercism/problem-specifications

The best way to fix an issue with the tests is to open a pull request there to change the above repo and after that is merged, then open one here to update these tests to match the new specification.

**Comment by wolf99** [comment]
Beat me to it by moments @siebenschlaefer , but your answer was better! 😀

**Comment by AfterRace** [comment]
@wolf99 I get your point

**Comment by AfterRace** [comment]
@wolf99 I get your point, I closed the issue because no action items are needed
