### ISSUE TITLE
C runs all tests the first time.

### ISSUE THREAD

**Issue by Gamecock** [exercism/c#167]
Normally in TDD you get one test to fail, get it to pass, refactor, start on next test.  In the C track all tests run the first time you build.
We could use the macros from cpp fairly easily.  
```
#if defined(EXERCISM_RUN_ALL_TESTS)
#endif
```
I happy to contribute to this effort if we want to do it.  I might need some guidance on everywhere we need to change.

**Comment by patricksjackson** [comment]
To add this you'd need to make that modification to all of the test suites and change the make call in [bin\run-tests](https://github.com/exercism/c/blob/876941a8ee876439ea4863a4ccb131664d677145/bin/run-tests#L27) (I believe to `make -DEXERCISM_RUN_ALL_TESTS clean >> /dev/null`, but I may have confused the syntax for that call.)

If I recall correctly, the reason I didn't bring this up before is that you need to add the #define's around the calls to `RUN_TEST` that are at the bottom of the test suite files, and adding them around the function definitions is optional. Since normally when you do the problem you tend to just look at the function definitions, it's a little clunkier for the end-user in this repo than it is in cpp where each test doesn't need to be listed twice.

Depending on how this ultimately looks to the end-user it might not be a given that this should go in. I'd suggest waiting for @ryanplusplus to weigh in until working on it.

(Alternatively, we could probably hack together a way to do it the way cpp (Boost Test) does, so essentially get rid of the `main()` definition in the test suite file.)

**Comment by ryanplusplus** [comment]
@patricksjackson an alternative is to do some source modification within the CI test script. For instance, we could find all commented lines within the test file's `main()` and uncomment them on the fly. This wouldn't be too difficult and avoids leaving anything confusing looking inside of the test files. We already do something similar when we move the skeleton out of the way and replace it with the examples.

Thoughts?

**Comment by Gamecock** [comment]
How do you run the `bin\run-tests`?  I need to figure that out, and then I can update the appropriate documentation page.
Once I've done that I might have a better idea of how to implement it.  I can dig around in Unity a little also.

**Comment by ryanplusplus** [comment]
@Gamecock if you're on MacOS or Linux, you can just execute `./bin/run-tests` in the terminal. If you're on Windows, you should be able to do the same from Cygwin. You also have the option of running Ubuntu on Windows: https://msdn.microsoft.com/en-us/commandline/wsl/about

**Comment by patricksjackson** [comment]
@ryanplusplus running all the tests from CI isn't what I'm that concerned about (the `#ifdef` way is common in most of the codebases I work on, so I'd support using that instead of bare comments even though it does lose the flexibility of commenting out individual `RUN_TEST` lines). My concern is the user experience when someone does the exercise.

In the Cpp track for example, you start by running one test and then open up others by moving a single `#ifdef` line past the next test you want to start testing against. It works well because you only need to look at the test functions themselves and move that one ifdef line to open up a new test, and it's all right in front of you. See [here](https://github.com/exercism/cpp/blob/master/exercises/allergies/allergies_test.cpp) for example.

For Unity they'd need to uncomment a totally different section of the file that they probably can't initially see and they need to keep track of which one they're working on to uncomment next (which is difficult since the names of them are long and somewhat similar). Actually, they probably have to uncomment both the function and the `RUN_TEST` macro since the compilation would fail due to the unused function, but that could be fixed.

I'm not pushing one way or the other, just that the end user experience should be kept in mind whenever we change the way they interact with the tests.

**Comment by ryanplusplus** [comment]
Ah, got it.

**Comment by Gamecock** [comment]
`   TEST_IGNORE_MESSAGE("Delete this line after the above test passes")`
I found this digging through the Unity headers trying to understand one of the other issues.  It works, but I still need to figure out how to override for the CI build.  Where would I look for that script?

**Comment by ryanplusplus** [comment]
@Gamecock this is the test script run by the CI build: https://github.com/exercism/c/blob/master/bin/run-tests.

So, having not looked through the Unity headers, how do you use that? Does it ignore all tests that follow that? Or does it ignore the test that immediately follows?

**Comment by Gamecock** [comment]
You put it as the first line inside the test case, I can do a PR for you to
look at and reject if you want.
Still need to undef it for the CI, I think I know what that looks like in
my head, I'll share when I have it working in code.

**Comment by Gamecock** [comment]
It's more like the @Ignore in junit, you add it one per test, but as the first line in the body.  I'll put together an example PR for one test set, and if that looks good we can discuss how to roll it to everything.

**Comment by ryanplusplus** [comment]
@Gamecock is this good to go?
