### ISSUE TITLE
Anagram: Memory management

### ISSUE THREAD

**Issue by NobbZ** [exercism/c#183]
The current implementation of the exercise, does require the student to use `xalloc`, but the allocated memory is then `free`d in the testsuite.

This makes the student unaware of the problems a `xalloc` can bring with it. I'd suggest therefore to change the test in a way that memory is allocated **and** freed by the student, by requiring him to have “constructors”, “destructors”, and “accessors” for the `Vector`.

If this is considered beyond the scope of this exercise, we should provide those functions and remove the label “memory management".

**Comment by ryanplusplus** [comment]
:-1:

**Comment by Gamecock** [comment]
@ryanplusplus which way do you want to go on this exercise, I can do the second choice, #169 discussed the difficulties in detecting a memory leak, probably beyond my skill level without a lot of help.

**Comment by wolf99** [comment]
Seeing as the exercise is about string matching I would opine that if changing it, it would be better to make it solely about that, reducing anything else to as simple as it can be. 

If that does not make it *too* simple then in respect of the latter maybe we should remove any memory allocation requirement at all? 

As the arguments provided to the implementation consist of the string and known anagram candidates then the work is in producing a Boolean result for each candidate. with this in mind the array within Vector could me changed from being an array of `char *` to an array of `struct candidate` where such a structure holds the known candidate and an Boolean variable of unknown value, the latter being where the implementation should place the result of its determination.

Then the initialisation for a test might look like:
````
   struct candidate candidates[] = {
      { false, "hello" },
      { false, "world" },
      { false, "zombies" },
      { false, "pants" }
   };

   struct Vector vin = {
      inputs,
      sizeof(candidates) / CANDIDATE_SIZE
   };
````

Just a suggestion as I'm aware this probably stretches the canonical description of "select the correct sublist" and "return a list".

**Comment by ryanplusplus** [comment]
@wolf99 sold me, I think we should go with the candidate structure option and avoid memory allocation entirely. C will have plenty of opportunities to show off manual memory management and I think it's generally important to show that there are alternatives to using dynamic memory.

**Comment by patricksjackson** [comment]
I am totally open to all work to reduce having to deal with memory management except in problems where that's the goal :)

Just to point out how hard this example solution is, it currently contains a pretty horrible memory allocation bug that hasn't been pointed out yet. I've looked at this problem before and not seen it either.

Because despite what it might look like, the array within the Vector struct (declared `char (*vec)[LEN];`) is not an array of `char*` (that would be `char* (vec)[LEN];`), or even a pointer to an array of `char*`'s (`char* (*vec)[LEN];`), it is a pointer to a 1D array of char's that used to point to the first row of a 2D array of chars. The solution actually _increments that pointer_ to point to the next string.

```
char (*vout_vecp)[MAX_STR_LEN] = vout.vec;
...
vout_vecp++; // Wut?
```

This moves the pointer to point to the next "1D array of chars" in memory, which just so happens to be how a 2D array is constructed.

If it was an array of `char*`'s pointing to the strings, then the way the test suite frees the memory wouldn't satisfy valgrind. It only works because it's allocated in one block by the example program. The solution didn't even get it correct either, it only allocates space for `sizeof(char*)` strings, which is an absolute _nightmare_ of a memory bug. I know I switch between 32 and 64 bit binaries all the time, and debugging this when it starts to hit would be horrific.

You might ask why this even compiles, given we flag all the compiler warnings. That's because C is very lax about transforming arrays to `char*`'s.

I am all for keeping this ridiculous memory allocation problem, but the difficulty needs to be marked as 10 and it needs to be dead last (until we write some even more diabolical memory allocation problem, which is actually a good idea, maybe even just a linked list, real Vector class, or hash table with LL buckets). Actually, I'd be all for collaborating between the C and Cpp tracks to come up with a test suite for a 'build a hash table' problem...

**Comment by wolf99** [comment]
OMG, that is a howler! Well caught indeed @patricksjackson 

WRT whether it should be a primarily a memory allocation problem or a string problem (it could of course be both, either). There are quite a few other exercise that deal with memory allocation at various levels. But as far as I can tell, this is the only exercise to use `qsort()`, which can be a hurdle in itself to people that may already be struggling, etc and so should be the latter. Just my 2c of course 💵.

**Comment by Gamecock** [comment]
If I am reading this thread write, does this capture the consensus:
There are two issues.
1.  Anagram should be modified to not require dynamic memory, per @wolf99 suggestion, and just teach qsort.
2. We should have some better memory management exercises.

**Comment by Gamecock** [comment]
Any reason not to do 
```struct candidate {
   bool is_anagram;
   char * word ;
};

struct candidates{
         struct candidate * candidate
         int length
```
No reason to copy all the words is there?

and make the declaration

`void anagrams_for(char* word,  struct candidates * candidates)`

By the way, it appears I've stumbled on another inconsistency.  If we name the variables in header declarations or not.  Could not find in kernal standards, but looking in the kernal they use names in a declaration, but not when externing.  I'll start writing either way.  

A maintainer can decide if it deserves a separate issue to go through and clean everything up.

**Comment by ryanplusplus** [comment]
@Gamecock I think we should definitely go with that simplification.

I think we should name the variables in header declarations if only because it will make it more clear to the user what the arguments in the provided signature means.
