### ISSUE TITLE
Anagram is nested too deep in config.json

### ISSUE THREAD

**Issue by wolf99** [exercism/c#250]
In #227 it was [decided](https://github.com/exercism/c/pull/227#discussion_r150229995) that more than one level of locking in the `config.json` was not a desirable thing. Looking at the visualization of the current `config.json` file we can see that the `anagram` exercise has this undesired multiple levels of lock.

![image](https://user-images.githubusercontent.com/281700/33931050-cdb4091a-dfe6-11e7-8619-c96f985217a2.png)

Where would be the best place to move the exercise in the ordering such that it does not suffer double-locking? Obviously it is thematically related to `acronym` and `pangram` but the current difficulty level of `5` suggests that it should be later in the track, possibly somewhere near `allergies`?

PS: Also note that there are two floating exercises -- this may also need rectifying.

PPS: FYI the config visualizer is at https://jonmcalder.shinyapps.io/exercism-config-viz/

**Comment by ryanplusplus** [comment]
I think that we could probably drop `anagram` in as a child of `isogram` because the "side quest" exercises are optional and don't need to be completed to progress.

However, we have quite a few exercises that don't open up side exercises, so maybe we should add `leap` to `grains`, `raindrops` to `beer-song`, and drop `anagram` in at `allergies` or `binary-search`?

**Comment by wolf99** [comment]
Closed by #251
