### ISSUE TITLE
Where is CI setup configured?

### ISSUE THREAD

**Issue by wolf99** [exercism/c#273]
Is the CI setup configured somewhere? Or maybe it is inherent in exercism's Travis account?

What I mean is, when Travis checks are run we can see a lot of output about what OS is used, what compilers are installed, which git repo to clone. I know that some of this, such as OS, is set in the `.travis.yml` file, but some is not. 

My main reason for asking is curiosity as I haven't done CI of my own before 🤔. But also I see from the output that both clang and GCC are installed and I know the compiler is called via the `cc` environment variable, so is `cc` explicitly set somewhere? Or does it default to one of the compilers and if so which? (IIRC `cc` is an indirect alias to GCC on Ubuntu, not sure if it is the same here)

**Comment by patricksjackson** [comment]
Most of the setup is done in `.travis.yml`, or this repo just uses travis defaults. There are some travis options that can be setup per repo (like caching between runs, which is extremely useful if you need to build big dependencies from source for example) but I don't think most of them are really useful here.

Travis does set CC and CXX to some default (I _think_ GCC but I'm not certain). Here is Travis's documentation on what you can do for building C projects - https://docs.travis-ci.com/user/languages/c/

The travis setup here could definitely use an update, but since there aren't too many new C features being used and it already has a valgrind check it's probably not too big a deal.

I did a pass on the travis setup for the Cpp repo a while ago, so it has a slightly more modern setup that tests against specific clang/gcc versions. Feel free to steal from that, though any of the big C or Cpp projects on Github probably have a much better setup.
https://github.com/exercism/cpp/blob/master/.travis.yml

**Comment by wolf99** [comment]
Thanks Patrick!
