### ISSUE TITLE
missing src directory when fetching binary_search_tree

### ISSUE THREAD

**Issue by kgashok** [exercism/c#295]
When fetching this exercise, the `/src` directory was missing. Is that to be expected?

**Comment by ryanplusplus** [comment]
It is not necessarily desirable, but it is expected. Some exercises contain a skeleton of the solution in the form of a provided .c and/or .h file. When one of these is included, the `/src` directory is automatically added (since the .c/.h files are in there). When none of these files are included, the `/src` directory is empty and the Exercism CLI tool does not create empty directories.

**Comment by kgashok** [comment]
Would it be desirable to add one?

**Comment by wolf99** [comment]
As the exercise is marked with a difficulty of 6, and the fact that it is non-core, IMO noit is not desirable to add a .c or .h file. By the time students reach this level they should be comfortable creating with the structure of the exercises and know that they will likely need to implement a source and header file.
