### ISSUE TITLE
Minesweeper tests don't properly free memory

### ISSUE THREAD

**Issue by redsled84** [exercism/c#297]
The *free_all* method to free all the memory associated with the output is half-baked. The current method:
```c
static void free_all(char **field)
{
   free(field[0]);
   free(field);
}
```

If it isn't already apparent, we aren't freeing all the strings within the string array. My fix:
```c
static void free_all(char **field, const size_t rows)
{
   for (unsigned long i = 0; i < rows; i++)
      free(field[i]);
   free(field);
}
```

All occurrences of *free_all* would have to have the rows added as an argument, but that's pretty trivial.

**Comment by ryanplusplus** [comment]
This is an interesting problem because the sample solution only calls `malloc` twice by allocating all rows at one time and then setting up pointers into the single allocated block. Given this, the current implementation of `free_all` is correct. However, if a user doesn't make this same optimization, the proposed `free_all` is needed.

I suspect that the right solution is to not free on behalf of the implementation and instead add a free/destroy method that will allow each implementation to manage the entire life cycle of its memory.

**Comment by redsled84** [comment]
Much better idea 👍
