### ISSUE TITLE
Directory and filename consistency

### ISSUE THREAD

**Issue by mikewalker** [exercism/c#312]
This is mainly a question regarding consistency since its tripped me up a couple of times now. After fetching an exercise my normal course of action is as follows. 

- Create src directory (mkdir src)
- Create src files (touch src/exercisename.{c,h})

Its the touch command that is tripping me up since in the case of some exercises nucleotide-count for example this pattern breaks down. The reason is that the directory uses dashes between words, and the file names use underscores. Could we pick one and stick to it?

Just thought I'd throw this out there to see what others thought about it. Might be good to have fewer things to cause problems with beginners...

**Comment by ryanplusplus** [comment]
Hey @mikewalker the directory names are dictated by Exercism and must match exactly the name of the upstream exercise (ie: must have dashes as in https://github.com/exercism/problem-specificationst). For the actual file names, we use underscores because this is how files in C are generally named.

We could switch to using dashes for filenames, but for me this feels out of place in C. @patricksjackson, @wolf99 what are your thoughts?

**Comment by mikewalker** [comment]
If its part of an upstream maybe best to just leave things alone. :) I only mentioned it since it tripped me up a couple of times. I've adjusted my process now too, instead of assuming, I am now running make first to see what files its looking for which is probably a better approach. Maybe put a note in the readme?

**Comment by wolf99** [comment]
Hi @mikewalker, @ryanplusplus; Yes, this has frustrated me once or twice before myself. However I concur with Ryan; dashes are not idiomatic for C file names. We could indeed update the documentation in some way however - good idea 👍

**Comment by ryanplusplus** [comment]
Actually, it looks like we're already in the clear thanks to @wolf99! See https://github.com/exercism/c/blame/master/docs/TESTS.md#L22
