### ISSUE TITLE
gigasecond: simply adding a billion second fails in TZs without DST.

### ISSUE THREAD

**Issue by NobbZ** [exercism/c#319]
I can't explain why, but this is a fact we discovered today.

A simple `n + 1e9` fails with an our off ins such timezones if it falls into a timespan where the creator of the tests had DST.

I'm not sure if this is related to the canonical data or to the implementation of ``time.h`` in C, but I have not yet seen similar problems or heard thereof in other languages.

**Comment by wolf99** [comment]
Is there a bug report on this? I'd look into this but it seems to work OK on my system. I'm in UTC-0 with DST of +1 running tests on Ubuntu 18.04 with GNU GCC with stdlib.
I'd need further information to figure it out I think

**Comment by NobbZ** [comment]
Activate yourself a timezone that has no DST at all. The student in question I talked about this problem earlier today was in Moscow Time, where no DST applies since Oct'14 (https://en.wikipedia.org/wiki/Moscow_Time).

In his timezone the example solution fails.

**Comment by ryanplusplus** [comment]
@NobbZ good catch. This probably affects almost every track, right?

Do you know of an elegant solution to this? I'd imagine that we can test the current locale for DST and adjust the test based on this runtime test, but that will probably be confusing for a student.

**Comment by NobbZ** [comment]
As I said, I have never seen similar problem s on other tracks, I had posted at the problem-specifications repository if I were thinking it were more global.

I will try to reproduce the issue in other languages over the weekend. At least if deploy today doesn't break anything ;)

**Comment by ZapAnton** [comment]
When I ran into the problem, simply commenting the `date.tm_isdst = 0;` line in the test suite was
enough to pass the tests.

Could it be a solution for the issue on this track or would you prefer a more general one?

**Comment by ryanplusplus** [comment]
@ZapAnton I think that is just letting garbage from the stack fill that value. In your case, it probably was something non-zero, but this won't be a good general solution because it will vary for every student.

**Comment by DrJPizzle** [comment]
Firstly: Hi.

Secondly:
I think the issue here is mktime();

This will always make some assumptions about the daylight savings. I think a negative number in the tm_isdst field (make best guess as to if to apply DST) is generally the best approach if you are just given a system time and need to deal with it. This may have been what happened to @ZapAnton. 

However, I don't think this isn't what you seem to want here. It will do local to local correctly, but to test that you will need to know about DST in the testers location in the general case. You seem to just want an 'ignore all daylight saving times' version. This is what timegm() does (its specific to GMT, but I think that's fine). I.e. timegm() does exactly what mktime does, but assumes all "struct tm"s are from gmtime().

_However_ timegm() is not available on all systems. It is a very easy implementation however, mostly because there is not faffing with timezones etc.

I will make a pull request to do this calculation.

Note: if using GMT is not fine, and you need the time_t to be correct for your local time, this can be fixed by offsetting with mk_time of a zeroed out struct tm. I can make this change if someone wants.

**Comment by DrJPizzle** [comment]
See 344. I think it resolves the issue.

**Comment by patricksjackson** [comment]
Do we know if #344 resolved this problem? Or is this still waiting on confirmation?

**Comment by ryanplusplus** [comment]
I think we're good. Just forgot to link the PR to this issue.
