### ISSUE TITLE
Acronym: longest acronym not long enough

### ISSUE THREAD

**Issue by sesamemucho** [exercism/c#320]
I just encountered a solution (https://exercism.io/mentor/solutions/e1e840249aa34b3a8f1e0a99c8b21f1f) in which the student allocated a buffer the size of a char pointer: `char *acr = malloc(sizeof(char *));` instead of basing it on the length of the input phrase. As it happens, none of the acronyms in the tests are longer than 4 characters, so neither `make test` nor `make memcheck` catches this error.
I would recommend making a phrase that abbreviates to something, say, 10 characters long.

I can submit a PR -- just want to go through the correct process.

**Comment by wolf99** [comment]
Thanks for raising this @sesamemucho, this should probably be raised as a PR on the problem specification in the related repo so that the requirement changes drop down to the C track here and other language tracks also. 

Maybe raise a PR there first: https://github.com/exercism/problem-specifications/blob/master/exercises/acronym/canonical-data.json

(Though we dont mind you raising a PR here too once the problem spec PR is accepted! 😉 )

**Comment by wolf99** [comment]
Hi @sesamemucho, were you able to raise an issue or PR on the mentioned repo? If so could you reply here with a link to the one you raised? This lets us keep on track of how things are progressing. Thanks!

**Comment by sesamemucho** [comment]
Sorry! Super busy at work this week. I just submitted a PR, all on github.
First time for that way of doing a PR -- hope it works.

Thanks
Bob

**Comment by wolf99** [comment]
Thanks Bob! PR is https://github.com/exercism/problem-specifications/pull/1287, is now merged and closed
