### ISSUE TITLE
Static Array for Allergies?

### ISSUE THREAD

**Issue by mikewalker** [exercism/c#321]
I just got a comment from a mentor on the allergies exercise about why I was allocating memory. It made me wonder, why we are myself. The typedef is defined in the header that is part of the exercise, and the tests are feeing memory. I cannot change this without changing the exercise, so I am asking here. Should this be changed?

The comment was:
```

Why are you allocating the parameter list in get_allergens? Why simply not declaring it in allergen_list_t as static array of size ALLERGEN_COUNT? Something like the following:

typedef struct {
   int count;
   allergen_t allergens[ALLERGEN_COUNT];
} allergen_list_t;

then you can initialize it using memset instead of calloc. 
```

**Comment by ryanplusplus** [comment]
I agree that this is a bit weird. Given that we know exactly how big the result could be (and it isn't that big), we could return a pointer to  a static instance. The problem with this approach is that it means you can only have one allergen score at a time so code that got a score could later have the value of the "returned" score change under its feet. Instead, it would make more sense to simply return a result by value instead of using pointers at all. If we make a change I think this is the way to go.

**Comment by DrJPizzle** [comment]
Pointer to static instance is dangerous. In certain cases (confusingly including this one), this is fine and performant but I don't think what should be taught as the default behaviour to novices. Plus if the aim is performance: the bit mask was the way forwards...
Personally, it think the malloc()ed array is the natural choice to be teaching.

**Comment by ryanplusplus** [comment]
@DrJPizzle why a malloc()ed array instead of returning an array by value? Using malloc() is the more general solution, but we have plenty of exercises that use that approach. Additionally, it's surprisingly frequent that I find someone is unaware that an array can be passed or returned by value so this would both make sense (fixed size result) and would potentially teach a new skill.

**Comment by DrJPizzle** [comment]
I guess _because_ its the standard way lots of exercises would use. I think it's easy to see it from an experienced coders point of view, where knowing what malloc does and how to use it is a given. In that case then yes: new and interesting is good and malloc has it's issues. However, just personal opinion, this seems aimed at learning the basics: people who won't necessarily be aware of the contents of the other examples. I think in that context the least exposure to anything that's 'surprisingly uncommon knowledge' is best.

I think of it this way:
 To justify malloc to a new student as
> "This is one of the standard ways to pass around arrays. It lets them be any size."

is easy to understand and gives some insight into how c works in a way that's easy to digest. Following up with "as always the real story is more interesting..." flows pretty naturally if needed.

In contrast
> "In most modern settings, heap access and particularly heap manipulations are some of the most costly operations. In order to avoid these we can make use of the fact the maximum size of the returned array is quite small. To do this we will always assume the array is of the fixed maximum size it can be, which allows it to be allocated on the stack. Then when we fill it, we pad any invalid fields with invalid values then deep-copy to a stack allocated array on return. Note there is a handy shortcut for by simply returning the fixed size array.
Overall that's likely to be more performant for this particular maximum size, and we thought you should know how to do it that way."

Requires you to get to grips with a lot of things that are a lot more advanced c than the exercise would otherwise need. It also looks a little like we are making hidden assumptions (like it needs to be fast), which can be quite daunting as the thought process is often something like: what else do I not know that I'd need to to make progress.
Worse, that assumes someone explains it in that way. Otherwise it might be very easy to jump to incorrect conclusions and end up returning stack pointers etc.

I know the sample is not necessarily what the student will see, but it's not like the example needs to be fast for technical reasons and it may well be the go-to for a mentor.

Just my thoughts though, and I am making all kinds of assumptions about target audience for students _and_ mentors etc, so take them with little weight.

**Comment by mayurdw** [comment]
Hey!

Recently I was mentoring this solution and I was wondering why an enum pointer is used ( pardon my language, I am not great at using C jargon ). 

At work, we avoid using malloc because in most cases we know what will be the size. The only time we actually use malloc is when we don't know how much space we would need eg Caching files at startup. 

If I use the same logic here, we know the allergen count. We shouldn't have be malloc'ing space for the pointer at runtime. 

But if we do that, then I would suggest moving the free from the test to the student's solution ie student has to malloc as well as free the memory. They go hand-in-hand.

**Comment by ryanplusplus** [comment]
> But if we do that, then I would suggest moving the free from the test to the student's solution ie student has to malloc as well as free the memory. They go hand-in-hand.

:+1:

**Comment by mayurdw** [comment]
Do we know who looks over these issues and decides?

**Comment by ryanplusplus** [comment]
@patricksjackson, @wolf99, and I are maintainers of the track.

**Comment by ryanplusplus** [comment]
@mayurdw if you are interested in creating a pull request, I'd personally prefer to see the result returned by value. I appreciate @DrJPizzle's input, but I don't think it's necessary to start with the whys and whens of returning a complex type by value when many people are probably unaware that it's even an option. Start with mechanics and allow the discussions of best practices to follow.

**Comment by mayurdw** [comment]
Hey @ryanplusplus 
I don't get what you mean?

**Comment by ryanplusplus** [comment]
@mayurdw something like this:

```c
typedef struct {
  int blah[20];
} result_t;

result_t foo(...);
```

That is, the struct is returned by value instead of by reference (either by having having the client provide a pointer that should be written to or by having the implementation `malloc`ing the memory itself).

**Comment by wolf99** [comment]
The other alternative here is to have the size of the returned array actually be variable.
i.e. it only contains as many elements as it needs to list the allergens that a person is allergic to.

This would require either pre-counting the allergens that are allergic, or re-allocating the array every time a new allergen is to be added. IMO I would prefer the former as having a second very simple loop vs reallocating and copying an array every time through a single complex loop seems more logical from a learning perspective (happily it is probably also more performant)
