### ISSUE TITLE
Consider adding CFLAGS += -Wmissing-declarations to makefile

### ISSUE THREAD

**Issue by Alexhans** [exercism/c#351]
One correction I've seen is to make functions `static` when they're only going to be called from within the file.  

Since `-Wmissing-declarations` in `GCC` checks this I wondered if it should be added to the default `makefile`.

That would, of course, would require some changes in the `test/<exercise>.c` files with something like

    %s/^void test/void test

but it would probably help automate that problem and learners could also learn from that makefile for their own projects.

Something should also be done so that setUp and tearDown don't result in complaints from the compiler.

**Comment by Alexhans** [comment]
Just to clarify, the -Wmissing declarations would force students to make the functions they don't declare as `static`, which seems to be desirable.

Without the proposed changes proposed in the first comment the warning turned error is shown like so:
> test/test_grains.c:4:6: error: no previous declaration for ‘setUp’ [-Werror=missing-declarations]
>  void setUp(void)

Defining a different `CFLAGS` for the files under `src` seems to be a reasonable idea.

**Comment by ryanplusplus** [comment]
Hey @Alexhans, sorry I wasn't clear. I meant to ask how the `%s/^void test/void test` would prevent the test functions from being falsely flagged as having no previous declaration. It looks to me like it will replace all places where `void test` appears at the beginning of a line with the exact same text, but I'm not a `sed` guru so I may be misunderstanding the pattern or your intent.

**Comment by Alexhans** [comment]
Oh, that was a typo.

Meant to replace `void test` occurring at the beginning of a line with `static void test`.

    %s/^void test/static void test

**Comment by elyashiv** [comment]
It seems like the warning is a little cryptic. Is the point to save on repeating comments about static functions? Following the error message, I can see lots of students adding a declaration instead of making the function static (especially because the first result in google when searching for this warning tells me to do that).

**Comment by patricksjackson** [comment]
Yes, I believe the point is to enforce good practices (setting non-global functions as static) with the compiler instead of through comments. I agree though that the error is not great...I'd be somewhat against it for that reason.

The suggested changes to the test files might be worth doing regardless so that the test functions themselves are declared static as better examples.

The `setUp()` and `tearDown()` methods have declarations in the latest version of the test suite, so updating to the latest Unity version would fix those issues if it's decided to add the flag.

**Comment by Alexhans** [comment]
Indeed.  The point would be to force the students to confront the issue instead of possibly finding out about it later.  There's always a possibility that the mentor forgets to mention it.

If the students DO add a function declaration instead of making it static (They might go to the [top google answer](https://stackoverflow.com/questions/20229376/warning-no-previous-declaration-c)) the mentor can always talk to them about options but the issue will be confronted without any doubt.

It's also a healthy flag to include for students that might use exercism folders as a starting point.

**Comment by ryanplusplus** [comment]
:+1:

**Comment by wolf99** [comment]
Closed by #386 & #388
