### ISSUE TITLE
Flag for mismatch between declaration and implementation

### ISSUE THREAD

**Issue by elyashiv** [exercism/c#356]
Hi. I just looked at a solution for binary_search, and the student has submitted a header with the following line:
```c
int binary_search(int val, int *arr, size_t length);
```
The function returns int instead of a pointer, but the whole thing compiles without any warnings :disappointed:

Is there a way to get warning for that (casting int to int*, mismatch in return type)?

**Comment by patricksjackson** [comment]
I think that's because the test suite is explicitly casting the outputs. I think the warnings we've enabled should pop up something, but with the explicit casting that goes away.

https://github.com/exercism/c/blob/2009f1321fc711ba77e6f9b58ae98b657a1f4ba9/exercises/react/test/vendor/unity_internals.h#L606

Maybe changing the comparison from `TEST_ASSERT_EQUAL_PTR(actual, expected)` to `TEST_ASSERT(actual == expected)` would do it.

**Comment by elyashiv** [comment]
It will be nice to have a warning for the cast...

I noticed just later that there was no warning for the function mismatch because the header was not included in the c file.
