### ISSUE TITLE
Word-count test-suite and TEST_ASSERT_EQUAL_UINT8_ARRAY

### ISSUE THREAD

**Issue by bgraf** [exercism/c#357]
What's the rationale behind using `TEST_ASSERT_EQUAL_UINT8_ARRAY` instead of `TEST_ASSERT_EQUAL_STRING_LEN` in the test suite?

* The interface in `word_count.h` does not mention any requirements on memory that is not part of the output, yet the test case expects it to be zero'd.

* Given a scenario where I'd like to distinguish 10000 words but most of the times it's only around 10, applying `memset` on the whole space seems wasteful and counter-intuitive.

**Comment by ryanplusplus** [comment]
Most likely the author didn't consider the possibility of using `TEST_ASSERT_EQUAL_STRING_LEN`. I like the simplification, but I'm not sure that someone learning C will understand that `TEST_ASSERT_EQUAL_STRING_LEN` will require the result to be null-terminated. Although the requirement enforced by the test is a bit overkill, `TEST_ASSERT_EQUAL_UINT8_ARRAY` does at least make explicit what the expectation is.

**Comment by ShadowWolf387** [comment]
I just finished this little puzzle and yes it makes a difference. I assumed that null termination was enough because that is normal in C. Most of the test cases fail until you zero the entire text space. It looks and feels like a bug where the test program is accessing memory it shouldn't be in. I doubt many beginners could figure out half of the test program like I did. The test program forces you to do things you would never do normally.

**Comment by wolf99** [comment]
I'd say `TEST_ASSERT_EQUAL_STRING_LEN` wasn't used because it didn't exist in earlier releases of the test framework. The only available assert that was explicitly string related was `TEST_ASSERT_EQUAL_STRING` which is unsafe in this case as it expects the strings to be well-formed (i.e. null terminated).

I can see that it would be a high probability that a student with a little knowledge of C would not initially expect to be required to zero out a fill block rather than just the C-string length. Using `TEST_ASSERT_EQUAL_STRING_LEN` imposes no implementation design considerations other than those required by the null-termination requirement of a C-string. Happily, it also does not prevent the current interpretation either.

@ryanplusplus  While `TEST_ASSERT_EQUAL_UINT8_ARRAY` does make it explicit what is required, does it also remove the learning step of _discovering_ that null-termination is required for strings rather than just some arbitrary test design decision?

**Comment by bgraf** [comment]
>. I like the simplification, but I'm not sure that someone learning C will understand that `TEST_ASSERT_EQUAL_STRING_LEN` will require the result to be null-terminated. Although the requirement enforced by the test is a bit overkill, `TEST_ASSERT_EQUAL_UINT8_ARRAY` does at least make explicit what the expectation is.

I'd like to add that maybe learning what a C-string is, should be part of this exercise, explicitly. A short explanation and link to further documentation could be added to the top of the instructions of the exercise.

Personally I think it'd be preferable to do it right from the start and put a bit of learning burden onto absolute beginners and make it less counter-intuitive to those with basic or past knowledge of C.

@wolf99 thank you for actions taken

**Comment by ryanplusplus** [comment]
> I'd like to add that maybe learning what a C-string is, should be part of this exercise, explicitly. A short explanation and link to further documentation could be added to the top of the instructions of the exercise.

Great point. This is a great compromise that will let us be both clear and "correct" (in the C sense).

**Comment by wolf99** [comment]
Closed by #389
