### ISSUE TITLE
Does word_count expect the word_count function to clean up between invocations?

### ISSUE THREAD

**Issue by dwrz** [exercism/c#358]
I am new to C, so my apologies in advance if this is not clear, or not a bug.

When a string passed to the `word_count` function has less tokens than a preceding invocation, the preceding invocation's tokens may still be found at the indexes not overwritten by the current invocation. This causes tests to fail.

If I understand correctly, the exercise expects an array of `word_count_word_t` to be returned, with the indexes matching the occurrence of the words.

Thus the string: "one of each" should return something akin to:
`[{ text: "one",  count: 1},{text: "of", count: 1}, {text: "each", count: 1}]`

Suppose the next two strings are "one two three extra" and then "one two three". I am seeing the following output from the tests:
`[{ text: "one",  count: 1},{text: "two", count: 1}, {text: "three", count: 1}, {text: "extra", count: 1}]`

`[{ text: "one",  count: 1},{text: "two", count: 1}, {text: "three", count: 1}, {text: "extra", count: 1}]`

Whereas for the second string, I would have expected:
`[{ text: "one",  count: 1},{text: "two", count: 1}, {text: "three", count: 1}]`

Is the expectation that the `word_count` function zero out all indexes after the current string's words? If yes, why? Shouldn't this be the caller's responsibility (i.e., the test suite)?

**Comment by ryanplusplus** [comment]
Yes, the expectation is that `word_count` should zero out the unused locations in the output. The primary reasons for this are that:
- there is exactly one implementation and any number of callers so expecting the caller to have zeroed out the return value means expecting that to be done in multiple places instead of one
- it's the return value of `word_count` so it makes sense for it to have sole ownership of its value instead of sharing this responsibility with the caller

All that said, the interface to `word_count` is anything but "normal". In real world code I would probably expect `word_count` to malloc the output and indicate the number of entries instead of having a fixed size input that the client is expected to allocate only for `word_count` to null-terminate it.

**Comment by dwrz** [comment]
Cheers! Thanks a lot for explanation. 

That makes sense, although I guess I can sense the abnormality -- what you describe feels a lot saner. I know it's very unlikely in this context, but there's still this feeling of, "how do I know the caller hasn't populated data they need at the other indexes?" 

FWIW, as a beginner I would have appreciated some hint about this in either the README or the header. This exercise seems like a big jump from the preceding one on the track -- getting a handle of the string library, learning to use structs, pointers, and then this implicit expectation of the argument should be used (requiring printf's in the tests to discover).

In any case, appreciate the insights!

**Comment by ryanplusplus** [comment]
Yes, I see what you mean. I think the right solution is to make the interface to this component more sane and/or move it further along in the track.
