### ISSUE TITLE
test_word_count.c bug

### ISSUE THREAD

**Issue by ShadowWolf387** [exercism/c#367]
Line 10 of test_word_count.c needs to be changed to:
word_count_word_t expected_solution[MAX_WORDS+1];

As MAX_WORDS is = 20, the test sometimes crashes when the test program tries to access the 21st word for the excessive words test. It depends on the environment. Using Msys2 just running make test, no crash. Under Win7 with Dev-C++ and Mingw 8.1.0 executing it in a cmd window causes a crash. I'm honestly surprised this hasn't been found yet because it's writing to memory in never never land.

**Comment by ryanplusplus** [comment]
Can you create a pull request with this change?

**Comment by ShadowWolf387** [comment]
If I did it right, pull request done.

**Comment by patricksjackson** [comment]
@ShadowWolf387 You did that correctly, thanks! This is actually a bug I thought we were checking for, so I'm looking into preventing that happening again. (It's probably because the memory checking tools don't always validate the data segment accesses by default, so our valgrind run didn't see it because the memory that was being accessed was inside of that region).

(Also just FYI, if  you had happened to add something like "Closes #367" to your initial Pull Request message it would've closed this automatically - https://help.github.com/en/articles/closing-issues-using-keywords. I'm not saying you needed to, just letting you know a useful feature :) )
