### ISSUE TITLE
Recruiting additional maintainers for C

### ISSUE THREAD

**Issue by kytrinyx** [exercism/c#430]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by bergjohan** [comment]
I'm interested in becoming a maintainer!

My Exercism handle is `bergjohan` and
I've been coding C professionally since 2014.

I'm currently maintaining the [x86-64 assembly track](https://github.com/exercism/x86-64-assembly), which has some similarities with the C track. The tests are written in C using the same framework, Unity, and we both use Makefiles for building. I've also written the [C test runner](https://github.com/exercism/c-test-runner).

Some ideas I have, is to use [libclang](https://clang.llvm.org/doxygen/group__CINDEX.html) for writing a [representer](https://github.com/exercism/automated-analysis/blob/master/docs/representers/introduction.md). I belive this is something we will need for v3.

[The GNU C reference Manual](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html) and [The GNU C Library](https://www.gnu.org/software/libc/manual/html_mono/libc.html) might be worth having a look at when coming up with concept exercises for the track.

**Comment by sebito91** [comment]
I'd like to assist with the maintenance of the repo/track! I'm already one of the mentors and would be able to dedicated ~2-3 hrs/wk for this track!

**Comment by ryanplusplus** [comment]
I'm currently a maintainer and am happy to continue doing so but can't commit to 2-3 hours a week.

**Comment by wolf99** [comment]
I'm currently a maintainer and happy to continue. I can't honestly commit to X hours per week, sometimes a month goes by and I realise I haven't even logged into GitHub once (e.g. December just gone). Other times I'll put up a couple new exercises a week 😂.

**Comment by ondono** [comment]
I'm currently mentoring on the track and I'd want to help with maintenance.

I've been coding in C for more than a decade, although most of my experience is in embedded devices. I don't know how much I'll be able to commit weekly since I'm supposed to move in about a month or so, but at least 2h/week should be doable.

**Comment by patricksjackson** [comment]
Similarly, I am a current maintainer, happy to continue helping but not able to commit to multiple hours a week.

**Comment by l0nax** [comment]
I also wanna help this exercism by getting a maintainer.

**Comment by wolf99** [comment]
HI @l0nax I PM'd you on slack but maybe you have not seen. A good first PR for getting started as a maintainer would be to add yourself to the maintainers list at: https://github.com/exercism/c/blob/master/config/maintainers.json 

You can see a previous example of such a PR, here: https://github.com/exercism/c/pull/433
😃

**Comment by l0nax** [comment]
I will create a PR as soon as I'm at home.

**Comment by wolf99** [comment]
@l0nax No rush, just wanted to make sure you saw the suggestion if maybe you don't use slack often  😃

**Comment by SourangshuGhosh** [comment]
@ErikSchierboom I am very interested to be maintainer for C language. I have lot of repositories especially coded in C language, therefore I can contribute to the maximum in this community

**Comment by wolf99** [comment]
Hi @SourangshuGhosh thanks for saying hi!
Probably best to first get up to speed on what is going on with the track in v2 or v3 and raise some issues or PRs 😃 
See: https://exercism.io/become-a-maintainer

**Comment by ErikSchierboom** [comment]
@SourangshuGhosh I've sent you an email with the details on how to become a maintainer. Thanks so much for wanting to help!

**Comment by ErikSchierboom** [comment]
We're closing this issue as it was part of our push to implement the v3 version of this track and v3 has [just been released](https://exercism.org/blog/exercism-v3-has-launched).

New maintainer are always welcome though!
