### ISSUE TITLE
Fix indent.sh

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/c#472]
Different versions of `indent` produce slightly different output. One option is to update `indent.sh` to use a version of `indent` that is included in this repo (64-bit Linux and 64-bit MacOS builds are probably sufficient) so that we have tighter control over the version being used.

**Comment by elyashiv** [comment]
I guess the issue is with different default values. If this is the case, we can solve this by being more explicit about those defaults.

What version does travis use?

**Comment by ryanplusplus** [comment]
Travis uses whichever package is current for Bionic:
https://packages.ubuntu.com/search?keywords=indent

**Comment by patricksjackson** [comment]
Another option to consider is setting up a method to run the formatter in github actions in the pull request. So instead of manually having to fix the formatting we could just add a `/format` comment to the PR and have github format it instead, and we could control the versioning.

See https://github.com/exercism/cpp/pull/352 as one example.
