### ISSUE TITLE
Anagram exercise: unicode and case sensitivity

### ISSUE THREAD

**Issue by tadas-s** [exercism/c#667]
Hello,

Not sure if it's right place to ask.

I'm a little confused about [this test case][1]:

```c
static void test_unicode_anagrams(void)
{
   TEST_IGNORE();               // This is an extra credit test.  Delete this line to accept the challenge
   // These words don't make sense, they're just greek letters cobbled together.
   char inputs[][MAX_STR_LEN] = {
      "ΒΓΑ",
      "ΒΓΔ",
      "γβα"
   };

   char subject[] = { "ΑΒΓ" };

   candidates = build_candidates(*inputs, sizeof(inputs) / MAX_STR_LEN);
   enum anagram_status expected[] = { IS_ANAGRAM, NOT_ANAGRAM, NOT_ANAGRAM };

   find_anagrams(subject, &candidates);
   assert_correct_anagrams(&candidates, expected);
}
```

Third candidate "γβα", according to the test suite, is *not* an anagram of "ΑΒΓ". But, if I uppercase the candidate it's "ΓΒΑ". It's also not a case of visually similar characters - try this in your browser console:

```javascript
> "αβγ".toUpperCase() == "ΑΒΓ"
> true
```

According some other tests anagram code should ignore the letter case.

Am I missing something? Or is utf8 capable solution is not expected to be case insensitive?

Cheers,
Tadas

[1]: https://github.com/exercism/c/blob/main/exercises/practice/anagram/test_anagram.c#L298-L315

**Comment by patricksjackson** [comment]
Hmm, that test case was added with the original commit, I think before anybody currently active joined - https://github.com/exercism/c/commit/b9d352fdd4d4171e535d0620128eb390b6ba9e8a

It's not listed as a test at all in the problem-specifications, so this is homegrown and probably unique to this track: https://github.com/exercism/problem-specifications/blob/main/exercises/anagram/canonical-data.json

That is probably an oversight. In fact, the [example code](https://github.com/exercism/c/blob/main/exercises/practice/anagram/.meta/example.c#L26) doesn't do this correctly at all, since it looks at the individual `char`s and not the Unicode encoding. It's looking at anagrams of the individual bytes in the string which I highly doubt is valid.

I may not have context so I'd like another maintainer to weigh in, but if we can write this example with the std library without too much difficulty I say we try to fix it. Otherwise I'm happy just removing it. I haven't written utf8 compatible C code before, so I'm not sure what facilities exist.

**Comment by ryanplusplus** [comment]
@patricksjackson I agree. If this is do-able without contortions with the standard library then we should fix it, otherwise we should just remove it.

**Comment by wolf99** [comment]
The non-ASCII cases were removed from the specification in  https://github.com/exercism/problem-specifications/pull/414 due to https://github.com/exercism/problem-specifications/issues/413.
I suggest we likewise remove the tests here.
Will prepare a PR for this now.
