### ISSUE TITLE
C: passes locally, not online

### ISSUE THREAD

**Issue by blogscot** [exercism/c#698]
I've been working on the Isogram (easy) problem. On three different occasions solutions that worked locally were reported as failed on submission. 

On the first occasion the automatic verification claimed that the code didn't not include a necessary function prototype - which was true. I had a look at the local makefile to compare what flags it included. To my consternation, the flags should have picked this issue up before submission but didn't. 🤔

On two other occasions, I submitted solutions that passed tests locally, reported as failed by the automatic checker, but later found to be passing when I ran the solution in the Editor (by adding / removing some whitespace to let me check the code without making changes.) Below, is my latest solution that doesn't pass checking on submission but does pass in the Editor.
```c
#include "isogram.h"
#include <ctype.h>
#include <string.h>

bool is_isogram(const char phrase[]) {
  if (phrase == NULL) {
    return false;
  }
  char letters_found[26];
  unsigned int next = 0;

  for (unsigned short i = 0; i < strlen(phrase); i++) {
    char letter = tolower(phrase[i]);
    if (!isalpha(letter)) {
      continue;
    }
    if (strchr(letters_found, letter)) {
      return false;
    }
    letters_found[next++] = letter;
  }
  return true;
}
```
In a bizarre twist, I found that my previous 'passing' solution (iteration 4) failed locally this morning ??!! for one particular test (letters_found wasn't being reinitialised between runs when I used a constant variable).  When I submitted the solution above (iteration 5, with a constant value) that error was reported on submission for this solution.

-- Edit --
I notice now that the automatic checking *fell over* when I submitted iteration 2. I suspect that was because I had deleted iteration 1 previously (to cover up my shame).

**Comment by siebenschlaefer** [comment]
Hi, C mentor here.  
This solution looks good, but there are three issues, and I have some additional suggestions:

---

Line 9 defines the array `letters_found` but does not initialize it. That means its elements have an "indeterminate value", and reading such an element before you assign a value to it invokes undefined behavior. In practice probably the program will just interpret the bytes of the underlying memory cells as `char`, so the elements of that array can have any value.

Later the function calls `strchr()` which expects its first argument to be a null-terminated string. But that terminating null-byte might not exist and `strchr()` could read past-the-end of that array. Or one of those uninitialized elements is just that `letter` that you were searching for and the function returns `false` incorrectly.  
Also, what if you've already found all 26 letters. Then there would definitely no terminating null-byte within `letters_found`.

The simplest fix is to lengthen the array and initialize it: `char letters_found[27] = {0};`  
But there might be a better alternative, see further down below.

---

Lines 13 and 14 pass a `char` to `tolower()` and `isalpha()`.

These functions come with a catch: They take an `int` and their behavior is undefined if their argument is neither representable by an `unsigned char` nor equal to `EOF`. You should never pass a `char` or a `signed char` to those functions but always cast it to `unsigned char` first (see also [cppreference](https://en.cppreference.com/w/c/string/byte/isalpha)).

---

The condition of the `for` loop calls `strlen()`.

Some compilers are clever enough to figure out that the result of that call will be the same throughout the function and actually call `strlen()` only once. Other compilers might not be that smart and call `strlen()` for each iteration of the loop (see [stackoverflow](https://stackoverflow.com/q/2049480/1447760) and [underhanded.xcott.com](https://web.archive.org/web/20150419092635/http://underhanded.xcott.com/?page_id=15)).

You could store the result of `strlen()` in a variable before the loop. Or you could write that `for` loop in a slightly different way:
```c
for (size_t i = 0, len = strlen(phrase); i<len; i++)
// or
for (size_t i = 0; phrase[i];  i++)
// or
for (const char *cp = phrase; *cp; cp++)
    // use *cp
// or
for ( ; *phrase; phrase++)
    // use *phrase
```

---

The type of the variable `i` is `unsigned short`.

Officially an `unsigned short` has *at least* 16 bits. That might be too few for very long strings.

You could use `size_t` instead because that type is guaranteed to be able to represent the size of all objects.

---

This solution stores each new letter in the array `letters_found`, in the order of their appearance in the `phrase`. Then line 17 calls `strchr()` which performs a linear search over that array.

There's a simple and faster alternative: What if you could map each letter to a number in the range [0, 25]? Then you could store in `letters_found` at index `idx` whether you've already see the letter with the associated number `idx`. That would the linear search and would also fix the first issue.

**Comment by wolf99** [comment]
Hola,
C maintainer here.
Nothing jumps out at me from your code above that screams bug in the track.
Are you still seeing failure online with local passes, or has this ceased since the infrastructure disruption that @iHiD mentioned ?

**Comment by wolf99** [comment]
Or it could be #695 striking again?

**Comment by siebenschlaefer** [comment]
@wolf99 Or it's the uninitialized array?

**Comment by wolf99** [comment]
Possibly, probably even, but it's slightly odd that it passed locally but not online.
Theoretically there's no reason to expect undefined behavior to be consistent of course.

**Comment by iHiD** [comment]
Would the uninitalized array sometimes contain falsey values and sometimes contain truthy ones. The test that failed was one where it expected TRUE but got FALSE (or the other way around - i can't remember now).

**Comment by siebenschlaefer** [comment]
I see two possible cases (in practice, in theory it's not possible to reason about undefined behavior):
1. The underlying type of the array is `char`, an uninitialized array might "contain" 26 instances of `'x'`. Then if the parameter contains a single `'x'` the function thinks that it already has seen that character and returns `false`.
2. The array might not contain the `'x'` nor a terminating null-byte. Then `strchr()` will read past-the-end of the array and might interpret some memory cell as that searched-for `'x'`.

**Comment by blogscot** [comment]
> Are you still seeing failure online with local passes, or has this ceased since the infrastructure disruption that @iHiD mentioned ?
I've submitted solutions to other exercises without any issues. 

As I mentioned above I did encounter an initialisation problem with the char array. I had tried initialising it while dimensioning the array with a const variable (thereby avoiding a magic number) but the compiler said that was a no-no. I now see that it's happy initialising the array if I dimension it with a constant value. Compilers eh? Thanks for the other points about C's string handling. It seems C's string handling is fraught with pitfalls. 

Please feel free to close this issue.
