### ISSUE TITLE
Newer C standard

### ISSUE THREAD

**Issue by jtepe** [exercism/c#812]
Is there a reason the code is restricted to C99? Most common compilers ([gcc](https://gcc.gnu.org/wiki/C11Status), [clang](https://clang.llvm.org/c_status.html)) are already supporting C17.

This issue #53 is back from 2016. Today, learning the language means learning the newer versions. I can't see a reason for sticking to such old standards.

**Comment by wolf99** [comment]
Hi!
Thanks for the good question and for finding and referencing the past question!

GCC and Clang do indeed support recent C standards in _hosted_ environments (e.g. environments with an OS).

However C is still used heavily in non-hosted environments (bare-metal, RTOS, near-hosted, etc). These environments usually only support much older versions of C. Additionally Microsoft's MSVC only supports C to C99 (last I looked, the situation may have changed since; but C is always second citizen to C++ for MS).

Thus having an older standard caters to the lowest common denominator of students that may use the track.

That said, I don't know if this is something we specifically aim for. FWIW I have no specific objection to moving to newer standards. 

Off the top of my head however I can't think of any currently existing exercise on the track that would make use any of the features of the newer standards (I'm not super familiar with the new features either!). 

Are there any specific features that you had in mind?

**Comment by siebenschlaefer** [comment]
No objections from my side, I'm fine with either.

Just out of curiosity: Would that have any impact on the solutions?
I'm not aware of any exercise where a C11 or C17 solution would look significantly different.

**Comment by jtepe** [comment]
@wolf99 Non-hosted environments are a valid point. However, I look at it from the other side. Learning C as it is now should be the goal. Later you can easily restrict the features you use and adapt to a more limited environment. IMO, learning the language should not be restricted because of that.

@siebenschlaefer No, the exercises (haven't solved all yet) are also solvable with older versions. But I found using newer features often made it easier.

**Comment by siebenschlaefer** [comment]
> But I found using newer features often made it easier.

That's what I wanted to know. Do you have an example for that?

**Comment by jtepe** [comment]
I thougth that most of the "quality of life" improvements I use came from C11 onwards, but looking it up it appears most of them have been introduced by C99 already.

For example, compound literals:
```c
int *p = (int [2]){1, 2};
```
Or array initialization with designators:
```c
int a[] = { [2] = 3 };
```
For C11 I can only point to anonymous struct members:
```c
struct foo {
    int i;
    struct {
        int a;
        int b;
    };
};
...
struct foo f = { .i = 10, .a = 200, .b = 300, };
...
```
Other than that, I regularly use bounds-checking versions of functions (e.g. `strcpy_s` instead of `strcpy`) were appropriate.

IMO multithreading is a major addition from C11 that is worth learning. But that can be an extension to the already existing exercises. Would a PR that adds such types of exercises be welcome?

I think we can close this issue ;)

**Comment by wolf99** [comment]
It would be good to have a submission for an exercise that demonstrates multithreading!

However I don't know if we have a way of requiring a multithreaded implementation to any exercise via the test framework.

If you have ideas for how to do it it would be good to hear it

(Bear in mind that exercises on any track are implementations of problem specifications from the problem specs repo)
