### ISSUE TITLE
Sum Of Multiples - incorrect tests

### ISSUE THREAD

**Issue by hakbraley** [exercism/c#896]
The instructions for this exercise say to include all multiples that are less than OR EQUAL TO the limit, but the tests show that it only wants values that are less than the limit.

Either the instructions or the tests need to be changed for this exercise.

**Comment by siebenschlaefer** [comment]
Thank you for reporting the issue.  

You are right, and the instructions have already been fixed in the [problem-specification repository](https://github.com/exercism/problem-specifications/blob/main/exercises/sum-of-multiples/instructions.md?plain=1#L12-L21).

Now these changes have to be copied to the C track. I'm sure the maintainers will do that soon (right, folks?)

**Comment by ryanplusplus** [comment]
I have a busy few days but can get it soon if no one else picks it up.
